### PR TITLE
adding utils.isRoot function

### PR DESCRIPTION
**Pull request by phillipskevin**
Closes https://github.com/stealjs/system-npm/issues/104.

### CODE REVIEW

**Comment by matthewp** [comment]
This should be `utils.pkg.isRoot`.  Also a function like `utils.pkg.default(loader)` to return `loader.npmPaths.__default` would be good.

**Comment by phillipskevin** [comment]
Ok, I'll make those changes.

**Comment by phillipskevin** [comment]
@matthewp I don't think my change would have caused the error in CI. Should I just try re-running the CI task? Or do I need to look into this error?

**Comment by matthewp** [comment]
I just restarted it

**Comment by matthewp** [comment]
This is released as system-npm 0.5.4

**Pull request merged**
