### PR TITLE
Progressively loaded package.jsons

### PR DESCRIPTION
**Pull request by matthewp**
This fixes two issues, #3, the ability to load modules that follow the `folder/index.js` convention, and #41, loading package.jsons only as needed during loading.

Longer explanations are available in cee5eeb950a8ab9bea9940b4ad8f24ef863567f0 and 1603e6dc37cea1ebf67a3b2dedf452e0f80e95ee

### CODE REVIEW

**Comment by matthewp** [comment]
Fix https://github.com/stealjs/system-npm/issues/99 with this

**Comment by justinbmeyer** [comment]
@matthewp If I'm understanding this right, does this add 1000 files to the repo?

If it does, couldn't we copy those files in place as part of the test setup?

**Comment by matthewp** [comment]
We could but it's probably too late now, they're already part of the history.

**Comment by justinbmeyer** [comment]
@matthewp I'm alright rewriting history :-) I'm basically the marty micfly of git.  Hopefully we don't make anyone's hands disappear. Lets talk about it tomorrow.

**Pull request merged**
